Repository I-question-this/red-bot-dad-cog, pull requests merged in 2020-11, with the labels that each got.

#88 Partial Issue 53
  jokes/chores.py
Labels: enhancement

#87 Simply LOTR joke
  AUTHORS.md
  README.md
  images/simply/001.gif
  images/simply/002.gif
  images/simply/003.gif
  images/simply/004.gif
  images/simply/005.gif
  images/simply/006.gif
  images/simply/007.gif
  images/simply/008.gif
  images/simply/009.gif
  images/simply/010.gif
  jokes/__init__.py
  jokes/simply.py
  jokes/util.py
Labels: enhancement

#90 Added bonk feature issue #89
  README.md
  images/bonk/001.gif
  images/bonk/002.gif
  images/bonk/003.gif
  images/bonk/004.gif
  images/bonk/005.gif
  images/bonk/006.gif
  images/bonk/007.gif
  images/bonk/008.gif
  images/bonk/009.gif
  images/bonk/010.gif
  images/bonk/011.gif
  images/bonk/012.gif
  images/bonk/013.gif
  images/bonk/014.gif
  images/bonk/015.gif
  jokes/__init__.py
  jokes/bonk.py
  jokes/favoritsm.py
  jokes/util.py
Labels: enhancement

#92 Adds "senpai notice me!" as a joke.
  README.md
  images/senpai/01.gif
  images/senpai/02.gif
  images/senpai/03.gif
  images/senpai/04.gif
  images/senpai/05.gif
  images/senpai/06.gif
  images/senpai/07.gif
  images/senpai/08.gif
  images/senpai/09.gif
  images/senpai/10.gif
  images/senpai/11.gif
  images/senpai/12.gif
  images/senpai/13.gif
  images/senpai/14.gif
  images/senpai/15.gif
  images/senpai/16.gif
  images/senpai/17.gif
  images/senpai/18.gif
  jokes/__init__.py
  jokes/senpai.py
  jokes/util.py
Labels: enhancement

#97 AdDs SpOnGeBoB cHiCkEn CaSe JoKe
  README.md
  images/spongebob_chicken/01.gif
  images/spongebob_chicken/02.gif
  images/spongebob_chicken/03.gif
  images/spongebob_chicken/04.gif
  images/spongebob_chicken/05.gif
  images/spongebob_chicken/06.gif
  jokes/__init__.py
  jokes/spongebob_chicken.py
  jokes/util.py
Labels: enhancement

#100 Seperates naughty and bonk gifs
  images/bonk/005.gif
  images/bonk/007.gif
  images/bonk/014.gif
  images/bonk/015.gif
  images/naughty/01.gif
  images/naughty/02.gif
  jokes/naughty.py
  jokes/util.py
Labels: bug, refactor

#103 No MoRe SpOnGeBoB mOcKiNg FoR eMpTy MeSsAgEs
  jokes/spongebob_chicken.py
Labels: bug
